apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-eks
  labels:
    app: hello-eks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-eks
  template:
    metadata:
      labels:
        app: hello-eks
    spec:
      containers:
      - name: hello-eks
        image: __IMAGE__
        ports:
        - containerPort: 8080
        env:
        - name: BUCKET
          value: "__BUCKET__"
        - name: AWS_REGION
          value: "__REGION__"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_SECRET_ACCESS_KEY
        readinessProbe:
          httpGet: { path: /, port: 8080 }
          initialDelaySeconds: 5
        livenessProbe:
          httpGet: { path: /, port: 8080 }
          initialDelaySeconds: 10
